name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
      - "web/**"
      - .github/workflows/web.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::836386213271:role/AdminRole
        role-duration-seconds: 1200

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 19

    - name: Install dependencies
      run: |
        cd web
        npm install

    # - name: Run tests
    #   run: npm run test:headless

    - name: Build
      run: |
        cd web
        ng build

    - name: Deploy
      if: success()
      run: |
        cd web
        aws s3 sync ./dist/web s3://arn:aws:s3:us-east-1:836386213271:easy-thank-you-notes-web